### ISSUE TITLE
Sync Script doesn't seem to work with description

### ISSUE THREAD

**Issue by NatoBoram** [OpenUserJS/OpenUserJS.org#1756]
Hi!

I've imported a script from GitHub and enabled the Webhook. However, when I publish changes and click on "Edit script info", the old info is still here.

The webhook have a response `200`, but nothing changed on the website.

```yaml
Date: Wed, 09 Sep 2020 14:41:51 GMT
Strict-Transport-Security: max-age=31536000000; includeSubDomains
Vary: X-HTTP-Method-Override
X-Powered-By: Express
```
